# Generated by Django 4.2.6 on 2023-10-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='actuality',
            field=models.CharField(choices=[('Актуален', 'Актуален'), ('50 на 50', '50 на 50')], default=('Актуален', 'Актуален'), max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.URLField(null=True),
        ),


    ]
