# Generated by Django 4.2.6 on 2023-10-30 05:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_reviewbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
